name: Community Chess

on:
  issues:
    types: [opened]
  workflow_dispatch:

permissions:
  contents: write
  issues: write

jobs:
  apply-move:
    if: |
      github.event_name == 'workflow_dispatch' || (github.event_name == 'issues' && (startsWith(github.event.issue.title, 'chess|move|') || startsWith(github.event.issue.title, 'chess|reset')))
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install python-chess

      - name: Extract move from issue title
        id: extract
        shell: bash
        run: |
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            echo "move=" >> $GITHUB_OUTPUT
            echo "actor=${{ github.actor }}" >> $GITHUB_OUTPUT
            echo "reset=false" >> $GITHUB_OUTPUT
          else
            title='${{ github.event.issue.title }}'
            if echo "$title" | grep -qi '^chess|reset'; then
              echo "move=" >> $GITHUB_OUTPUT
              echo "reset=true" >> $GITHUB_OUTPUT
            else
              move=$(echo "$title" | awk -F'|' '{print $3}')
              echo "move=$move" >> $GITHUB_OUTPUT
              echo "reset=false" >> $GITHUB_OUTPUT
            fi
            echo "actor=${{ github.event.issue.user.login }}" >> $GITHUB_OUTPUT
          fi

      - name: Update README with chess board and moves
        env:
          CHESS_MOVE: ${{ steps.extract.outputs.move }}
          CHESS_ACTOR: ${{ steps.extract.outputs.actor }}
          CHESS_RESET: ${{ steps.extract.outputs.reset }}
        run: |
          if [ "$CHESS_RESET" = "true" ]; then
            python scripts/chess/update_readme.py --reset --actor "$CHESS_ACTOR"
          else
            python scripts/chess/update_readme.py --move "$CHESS_MOVE" --actor "$CHESS_ACTOR"
          fi

      - name: Commit and push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add README.md chess/state.txt || true
          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            msg="chess: update board"
            if [ -n "${{ steps.extract.outputs.move }}" ]; then
              msg="$msg (move ${{ steps.extract.outputs.move }})"
            fi
            if [ "${{ steps.extract.outputs.reset }}" = "true" ]; then
              msg="$msg (reset)"
            fi
            git commit -m "$msg"
            git push
          fi

      - name: Close issue (if any)
        if: github.event_name == 'issues'
        uses: peter-evans/close-issue@v3
        with:
          issue-number: ${{ github.event.issue.number }}
          comment: |
            Thanks @${{ github.event.issue.user.login }}! Processed move `${{ steps.extract.outputs.move }}`. The board has been updated in the README.
